addSbtPlugin("com.typesafe.play"        % "sbt-plugin"                % "2.8.8")
addSbtPlugin("org.foundweekends.giter8" % "sbt-giter8-scaffold"       % "0.11.0")
addSbtPlugin("com.typesafe.sbteclipse"  % "sbteclipse-plugin"         % "5.2.4")
addSbtPlugin("org.scala-js"             % "sbt-scalajs"               % "1.7.0")
addSbtPlugin("com.vmunier"              % "sbt-web-scalajs"           % "1.2.0")
addSbtPlugin("com.typesafe.sbt"         % "sbt-gzip"                  % "1.0.2")
addSbtPlugin("com.typesafe.sbt"         % "sbt-digest"                % "1.1.4")
addSbtPlugin("org.portable-scala"       % "sbt-scalajs-crossproject"  % "1.1.0")
// addSbtPlugin("net.virtual-void"         % "sbt-dependency-graph"      % "0.8.0")
// addDependencyTreePlugin
